---
language: python
python: "2.7"

sudo: required
dist: trusty

services:
  - mysql

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Activate ansible.cfg with Travis CI environment specific settings
  - cp tests/ansible.cfg.travis ansible.cfg

  # Create symlink for this role, to make it appear under its proper name
  - ln -s ansible-role-gogs ../nome.gogs

  # Install other roles required by tests
  - ansible-galaxy install jdauphant.nginx geerlingguy.mysql

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  # Run tests
  - ansible-playbook tests/test.yml -i tests/inventory -c local

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
