---
- name: Install build dependencies
  package: name=gcc state=present
  when: gogs_db_type == "sqlite3"

- name: Download Go
  get_url:
    url: https://storage.googleapis.com/golang/{{ gogs_golang_version }}.{{ golang_arch }}.tar.gz
    dest: "{{ gogs_user_home }}/{{ gogs_golang_version }}.{{ golang_arch }}.tar.gz"
  register: golang_tarball
- name: Create {{ gogs_goroot | dirname }}
  file: name={{ gogs_goroot | dirname }} state=directory owner={{ gogs_user }}
- name: Unpack Go
  unarchive:
    copy: no
    src: "{{ gogs_user_home }}/{{ gogs_golang_version }}.{{ golang_arch }}.tar.gz"
    dest: "{{ gogs_goroot | dirname }}"
    owner: "{{ gogs_user }}"
  when: golang_tarball.changed
- name: Create GOPATH
  file: name={{ gogs_gopath }} state=directory owner={{ gogs_user }}

- include: build.yml
  become: true
  become_user: "{{ gogs_user }}"

- name: Symlink build dir to {{ gogs_user_home }}/gogs
  file: src={{ gogs_user_home }}/go/src/github.com/gogits/gogs dest={{ gogs_user_home }}/gogs state=link
